In [199]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cpu


## Introduction to PyTorch


### Scaler


In [200]:
scaler = torch.tensor(7)
scaler


tensor(7)

In [201]:
scaler.ndim


0

In [202]:
scaler.shape


torch.Size([])

In [203]:
scaler.item()


7

### Vector


In [204]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector


tensor([1, 2, 3, 4, 5])

In [205]:
vector.ndim


1

In [206]:
vector.shape


torch.Size([5])

### Matrix


In [207]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [208]:
MATRIX.ndim


2

In [209]:
MATRIX.shape


torch.Size([2, 3])

In [210]:
MATRIX[0]


tensor([1, 2, 3])

In [211]:
MATRIX[1]


tensor([4, 5, 6])

### Tensor


In [212]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [213]:
TENSOR.ndim


3

In [214]:
TENSOR.shape


torch.Size([2, 2, 3])

In [215]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors


In [216]:
# Create a random tensor of shape (3, 5)
X = torch.rand(3, 5)
X


tensor([[0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317]])

In [217]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(3, 224, 224)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [218]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 5))
zeros


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [219]:
# create a tensor of all ones
ones = torch.ones(size=(3, 5))
ones


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [220]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [221]:
# Use torch.range and get deprecated warning, use torch.arange instead
one_to_ten = torch.arange(0, 10)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
# Use torch.range
one_to_ten2 = torch.arange(start=0, end=10, step=1.1)
one_to_ten2


tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])

In [223]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :

1. Tensor is not right data type
2. Tensor is not right shape
3. Tensor is not on right device


In [224]:
# float 32 tensor
float_32_tensor = torch.tensor(
    data=[1.1, 2.2, 3.3],  # the data to store in the tensor
    dtype=torch.float32,  # the data type of the tensor
    device=None,  # what device to store the tensor on (CPU, GPU)
    requires_grad=False,
)  # whether or not the tensor should be tracked by the gradient descent algorithm
float_32_tensor.dtype, float_32_tensor


(torch.float32, tensor([1.1000, 2.2000, 3.3000]))

In [225]:
float_16_tensor = float_32_tensor.type(torch.float16)  # convert to float 16
float_16_tensor.dtype, float_16_tensor


(torch.float16, tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16))

In [226]:
float_32_tensor * float_16_tensor


tensor([ 1.2096,  4.8383, 10.8926])

In [227]:
int_32_tensor = torch.tensor(data=[1, 2, 3])  # the data to store in the tensor
int_32_tensor.dtype, int_32_tensor


(torch.int64, tensor([1, 2, 3]))

In [228]:
float_32_tensor * int_32_tensor


tensor([1.1000, 4.4000, 9.9000])

## Getting information from tensors

1. Tensor is not right data type - to get data type form a tensor, can use `tensor.dtype`
2. Tensor is not right shape - to get data type form a tensor, can use `tensor.shape`
3. Tensor is not on right device - to get data type form a tensor, can use `tensor.device`


In [229]:
# create a tensor of random integers
random_int_tensor = torch.randint(low=0, high=10, size=(3, 3))
random_int_tensor


tensor([[6, 3, 6],
        [7, 5, 1],
        [2, 8, 8]])

In [230]:
# find out details about a tensor
print(random_int_tensor)
print(f"Data type of tensor: {random_int_tensor.dtype}")
print(f"Shape of tensor: {random_int_tensor.shape}")
print(f"Size of tensor: {random_int_tensor.size()}")
print(f"Device tensor is stored on: {random_int_tensor.device}")
print(f"Number of dimensions: {random_int_tensor.ndim}")


tensor([[6, 3, 6],
        [7, 5, 1],
        [2, 8, 8]])
Data type of tensor: torch.int64
Shape of tensor: torch.Size([3, 3])
Size of tensor: torch.Size([3, 3])
Device tensor is stored on: cpu
Number of dimensions: 2


### Manipulating tensors (tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [231]:
# create a tensor
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
tensor, tensor + 10


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [232]:
tensor - 10


tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [233]:
tensor * 10


tensor([[10, 20, 30],
        [40, 50, 60]])

In [234]:
tensor / 10


tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [235]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)


tensor([[10, 20, 30],
        [40, 50, 60]])

In [236]:
tensor**2


tensor([[ 1,  4,  9],
        [16, 25, 36]])

### Matrix Multiplication

Two main ways to perform matrix multiplication in PyTorch:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that perform matrix multiplication:

1. The inner dimensions must match
    - `(3,2) @ (3,2)` won't work
    - `(3,2) @ (2,3)` will work
    - `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the outer dimensions
    - `(3,2) @ (2,3)` will result in a `(3,3)` matrix
    - `(2,3) @ (3,2)` will result in a `(2,2)` matrix


In [237]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(2, 3)))


tensor([[0.7493, 0.9773, 0.2240],
        [0.5034, 0.5990, 0.1107],
        [1.2643, 1.8168, 0.4939]])

In [238]:
# Element-wise multiplication
print(tensor, "*", tensor, "=", torch.mul(tensor, tensor))


tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]]) = tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [239]:
# matrix multiplication
torch.matmul(tensor, tensor.T)


tensor([[14, 32],
        [32, 77]])

In [240]:
tensor, tensor.T


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [241]:
# matrix multiplication by hand
[1 * 1 + 2 * 2 + 3 * 3, 1 * 4 + 2 * 5 + 3 * 6], [
    4 * 1 + 5 * 2 + 6 * 3,
    4 * 4 + 5 * 5 + 6 * 6,
]


([14, 32], [32, 77])

In [242]:
!time
t = torch.tensor([1,2,3])
m =[]
value =0
for i in range(len(t)):
    value += t[i]*t[i]
    

print(value)

shell  0.00s user 0.01s system 2086% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total
tensor(14)


In [243]:
!time

torch.matmul(t,t)

shell  0.00s user 0.01s system 2129% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor(14)

In [244]:
!time 

torch.matmul(tensor, tensor.T)

shell  0.00s user 0.01s system 2170% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor([[14, 32],
        [32, 77]])

In [245]:
# @ operator for matrix multiplication
tensor @ tensor.T


tensor([[14, 32],
        [32, 77]])

### One of the most common error in deep learning: shape error


In [246]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
# torch.matmul(tensor_A, tensor_B) # error because of shape
torch.matmul(tensor_A.T, tensor_B), torch.matmul(tensor_A, tensor_B.T)


(tensor([[ 76, 103],
         [100, 136]]),
 tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]))

## Finding min, max, sum, mean, absolute value, standard deviation (tensor aggregation)


In [247]:
# create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [248]:
# find the min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [249]:
# find the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [250]:
# find the mean. note that the torch.mean() function requires a float32 tensor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [251]:
# find the sum
torch.sum(x), x.sum()


(tensor(450), tensor(450))

### finding the positional maximum and minimum


In [252]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [253]:
# find the position in tensor that has the minimum value

x.argmin(), x.min()


(tensor(0), tensor(0))

In [254]:
# find the position in tensor that has the maximum value

x.argmax(), x.max()


(tensor(9), tensor(90))

In [255]:
tensor_A, tensor_A.argmax()


(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor(5))

## Reshaping, stacking, squeezing, un-squeezing

-   Reshaping - reshape an input tensor to a defined shape
-   view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
-   stack - combine multiple tensors on top of each other (vertically - vstack) or side by side (horizontally h-stack)
-   squeeze - remove all `1` dimensions from a tensor
-   unsqueeze - add a dimension of size `1` to a tensor
-   permute - return a view of an input tensor with its dimensions permuted (swapper) in a certain order


In [256]:
x = torch.arange(1.0, 10.0)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [257]:
# add a dimension to the tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [258]:
x_reshaped2 = x.reshape(9, 1)
x_reshaped2, x_reshaped2.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [259]:
# change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [260]:
# changing z changes x (because they are the same tensor and shares the same memory)
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [261]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [262]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [263]:
# squeeze the tensor - remove all dimensions of size 1
x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [264]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [265]:
# unsqueeze the tensor - add a dimension of size 1

x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [266]:
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape


(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [267]:
# permute  - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # (height, width, channels)
x_original[0][0][0], x_original.shape


(tensor(0.1496), torch.Size([224, 224, 3]))

In [268]:
# permute the tensor to rearrange the dimensions
x_permuted = x_original.permute(2, 0, 1)  # (channels, height, width)
x_permuted[0][0][0], x_permuted.shape


(tensor(0.1496), torch.Size([3, 224, 224]))

In [269]:
x_permuted[0, 0, 0], x_permuted.shape


(tensor(0.1496), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

-   indexing with PyTorch is similar with numpy


In [270]:
# creating a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [271]:
# lets index on our new tensor

x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [272]:
# lets index on middle bracket (dim=1)
x[0, 0], x[0][0]  # both are same


(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [273]:
#  lets index on the most inner bracket (last dimension)
x[0, 0, 0], x[0][0][0]


(tensor(1), tensor(1))

In [274]:
#  you can use ":" to select "all" of a target dimension

x, x[:, 0], x[:, 0, 0], x[:, 0, 0][0]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3]]),
 tensor([1]),
 tensor(1))

In [275]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x, x[:, :, 1]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

In [276]:
#  get all values of the 0 dimension but only 1 index of 1st and 2nd dimensions
x, x[:, 1, 1], x[0, 1, 1]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([5]),
 tensor(5))

In [277]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x, x[0, 0, :], x[0, 0], x[0][0]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]))

In [278]:
# index on x to return 9

print(x, x[:, 2, 2], x[0, 2, 2])

# index on x to return 3, 6, 9

print(x, x[:, :, 2])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) tensor([9]) tensor(9)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

NumPy is a popular scientific numerical computing library for Python.

And because of this, PyTorch has functionality to interact with NumPy.

-   Data in NumPy, want in PyTorch tensors -> `torch.from_numpy(ndarray)`
-   PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [279]:
#  Numpy Array to Tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [280]:
# Change th evalue of array and waht will this do to `tensor`

array = array + 1
print(array, tensor)

tensor = tensor + 1

print(array, tensor)


[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
[2. 3. 4. 5. 6. 7. 8.] tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [281]:
#  tensor to numpy array
tensor = torch.arange(1.0, 8.0)
array = tensor.numpy()
tensor, array


(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [282]:
# Change the tensor and what will this do to `array`
tensor = tensor + 1
print(tensor, array)


tensor([2., 3., 4., 5., 6., 7., 8.]) [1. 2. 3. 4. 5. 6. 7.]


In [283]:
# Change the array and what will this do to `tensor`
array = array + 1
print(tensor, array)


tensor([2., 3., 4., 5., 6., 7., 8.]) [2. 3. 4. 5. 6. 7. 8.]


## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data ->again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness.


In [284]:
torch.rand(3, 3)  # will create always random numbers between 0 and 1


tensor([[0.2706, 0.6560, 0.6614],
        [0.3648, 0.1490, 0.8693],
        [0.0294, 0.5449, 0.0794]])

In [285]:
# create two random tensors
random_tensor_a = torch.rand(3, 3)
random_tensor_b = torch.rand(3, 3)


random_tensor_a, random_tensor_b, random_tensor_a == random_tensor_b


(tensor([[0.2313, 0.2927, 0.3386],
         [0.3708, 0.0831, 0.0944],
         [0.6568, 0.7708, 0.1053]]),
 tensor([[0.1467, 0.1932, 0.9118],
         [0.1488, 0.0913, 0.4470],
         [0.2440, 0.5571, 0.1928]]),
 tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]))

In [286]:
# Let's make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 3)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 3)

random_tensor_c, random_tensor_d, random_tensor_c == random_tensor_d


(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [287]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [288]:
torch.cuda.is_available()

False

In [289]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [290]:
#  Count number of devices
torch.cuda.device_count()

0

### 3. putting tensors (and models) on the GPU


In [291]:
#  creating a tensor on GPU
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [292]:
# move tensor to GPU

tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### Moving tensors back to CPU

In [293]:
#  if tensor is on GPU, can't transform in to numpy array
tensor_gpu.numpy()

array([1, 2, 3])

In [294]:
# to fix the GPU tensor with numpy issue, we can first set the tensor to CPU
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])