In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.0+cpu


## Introduction to PyTorch

### Scaler

In [8]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [10]:
scaler.ndim

0

In [12]:
scaler.shape

torch.Size([])

In [13]:
scaler.item()

7

### Vector

In [14]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector

tensor([1, 2, 3, 4, 5])

In [15]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([5])

In [18]:
vector.item()

RuntimeError: a Tensor with 5 elements cannot be converted to Scalar

### Matrix

In [19]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 3])

In [23]:
MATRIX[0]

tensor([1, 2, 3])

In [24]:
MATRIX[1]

tensor([4, 5, 6])

### Tensor

In [25]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [26]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([2, 2, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors

In [33]:
# Create a random tensor of shape (3, 5)
X = torch.rand(3, 5)
X

tensor([[0.9080, 0.8549, 0.0809, 0.3469, 0.8374],
        [0.5600, 0.8328, 0.8643, 0.7327, 0.5023],
        [0.1738, 0.6298, 0.5031, 0.8348, 0.3449]])

In [37]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [39]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [41]:
# create a tensor of all ones
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [42]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [53]:
# Use torch.range and get deprecated warning, use torch.arange instead
one_to_ten= torch.arange(0, 10)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# Use torch.range
one_to_ten2= torch.arange(start=0, end=10, step=1.1)
one_to_ten2


tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])

In [55]:
# creating tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :
    
        1. Tensor is not right data type
        2. Tensor is not right shape
        3. Tensor is not on right device

In [61]:
# float 32 tensor
float_32_tensor = torch.tensor(data=[1.1, 2.2, 3.3], # the data to store in the tensor
                               dtype=torch.float32, # the data type of the tensor
                               device=None, # what device to store the tensor on (CPU, GPU)
                               requires_grad=False) # whether or not the tensor should be tracked by the gradient descent algorithm
float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([1.1000, 2.2000, 3.3000]))

In [62]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert to float 16
float_16_tensor.dtype, float_16_tensor

(torch.float16, tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16))

In [63]:
float_32_tensor*float_16_tensor

tensor([ 1.2096,  4.8383, 10.8926])

In [64]:
int_32_tensor = torch.tensor(data=[1, 2, 3]) # the data to store in the tensor
int_32_tensor.dtype, int_32_tensor

(torch.int64, tensor([1, 2, 3]))

In [65]:
float_32_tensor * int_32_tensor

tensor([1.1000, 4.4000, 9.9000])

## Getting information from tensors
    
    1. Tensor is not right data type - to get data type form a tensor, can use `tensor.dtype`
    2. Tensor is not right shape - to get data type form a tensor, can use `tensor.shape`
    3. Tensor is not on right device - to get data type form a tensor, can use `tensor.device`

In [67]:
# create a tensor of random integers
random_int_tensor = torch.randint(low=0, high=10, size=(3, 3))
random_int_tensor

tensor([[7, 8, 6],
        [9, 7, 1],
        [7, 2, 1]])

In [71]:
# find out details about a tensor
print(random_int_tensor)
print(f"Data type of tensor: {random_int_tensor.dtype}")
print(f"Shape of tensor: {random_int_tensor.shape}")
print(f"Size of tensor: {random_int_tensor.size()}")
print(f"Device tensor is stored on: {random_int_tensor.device}")
print(f"Number of dimensions: {random_int_tensor.ndim}")


tensor([[7, 8, 6],
        [9, 7, 1],
        [7, 2, 1]])
Data type of tensor: torch.int64
Shape of tensor: torch.Size([3, 3])
Size of tensor: torch.Size([3, 3])
Device tensor is stored on: cpu
Number of dimensions: 2


### Manipulating tensors (tensor operations)

Tensor operations include:
    
        1. Addition
        2. Subtraction
        3. Multiplication
        4. Division
        5. Matrix Multiplication

In [72]:
# create a tensor
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
tensor, tensor+10

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [73]:
tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [74]:
tensor*10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [75]:
tensor/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [76]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)

tensor([[10, 20, 30],
        [40, 50, 60]])

In [77]:
tensor**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

### Matrix Multiplication
Two main ways to perform matrix multiplication in PyTorch:
    
        1. Element-wise multiplication
        2. Matrix multiplication (dot product)

In [80]:
# Element-wise multiplication
print(tensor,"*",tensor,"=",torch.mul(tensor, tensor))

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]]) = tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [82]:
# matrix multiplication
torch.matmul(tensor, tensor.T)


tensor([[14, 32],
        [32, 77]])

In [83]:
tensor,tensor.T

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [84]:
# matrix multiplication by hand
[1*1+2*2+3*3, 1*4+2*5+3*6], [4*1+5*2+6*3, 4*4+5*5+6*6]

([14, 32], [32, 77])

In [101]:
# %% time
m =[]
value =1
for i in range(tensor.shape[0]):
    for j in range(tensor.shape[1]):
        value += tensor[i][j]*tensor[i][j]
    print(i, value)
    # m[i] = value
    value=1

print(value)

0 tensor(15)
1 tensor(78)
1
