In [173]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.0+cpu


## Introduction to PyTorch

### Scaler

In [174]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [175]:
scaler.ndim

0

In [176]:
scaler.shape

torch.Size([])

In [177]:
scaler.item()

7

### Vector

In [178]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector

tensor([1, 2, 3, 4, 5])

In [179]:
vector.ndim

1

In [180]:
vector.shape

torch.Size([5])

### Matrix

In [181]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [182]:
MATRIX.ndim

2

In [183]:
MATRIX.shape

torch.Size([2, 3])

In [184]:
MATRIX[0]

tensor([1, 2, 3])

In [185]:
MATRIX[1]

tensor([4, 5, 6])

### Tensor

In [186]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [187]:
TENSOR.ndim

3

In [188]:
TENSOR.shape

torch.Size([2, 2, 3])

In [189]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors

In [190]:
# Create a random tensor of shape (3, 5)
X = torch.rand(3, 5)
X

tensor([[0.5187, 0.6821, 0.4497, 0.8339, 0.7510],
        [0.0935, 0.0520, 0.3138, 0.8661, 0.9951],
        [0.6827, 0.1093, 0.0961, 0.3993, 0.2016]])

In [191]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [192]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [193]:
# create a tensor of all ones
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [194]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [195]:
# Use torch.range and get deprecated warning, use torch.arange instead
one_to_ten= torch.arange(0, 10)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
# Use torch.range
one_to_ten2= torch.arange(start=0, end=10, step=1.1)
one_to_ten2


tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])

In [197]:
# creating tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :
    
        1. Tensor is not right data type
        2. Tensor is not right shape
        3. Tensor is not on right device

In [198]:
# float 32 tensor
float_32_tensor = torch.tensor(data=[1.1, 2.2, 3.3], # the data to store in the tensor
                               dtype=torch.float32, # the data type of the tensor
                               device=None, # what device to store the tensor on (CPU, GPU)
                               requires_grad=False) # whether or not the tensor should be tracked by the gradient descent algorithm
float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([1.1000, 2.2000, 3.3000]))

In [199]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert to float 16
float_16_tensor.dtype, float_16_tensor

(torch.float16, tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16))

In [200]:
float_32_tensor*float_16_tensor

tensor([ 1.2096,  4.8383, 10.8926])

In [201]:
int_32_tensor = torch.tensor(data=[1, 2, 3]) # the data to store in the tensor
int_32_tensor.dtype, int_32_tensor

(torch.int64, tensor([1, 2, 3]))

In [202]:
float_32_tensor * int_32_tensor

tensor([1.1000, 4.4000, 9.9000])

## Getting information from tensors
    
    1. Tensor is not right data type - to get data type form a tensor, can use `tensor.dtype`
    2. Tensor is not right shape - to get data type form a tensor, can use `tensor.shape`
    3. Tensor is not on right device - to get data type form a tensor, can use `tensor.device`

In [203]:
# create a tensor of random integers
random_int_tensor = torch.randint(low=0, high=10, size=(3, 3))
random_int_tensor

tensor([[2, 2, 3],
        [8, 3, 3],
        [6, 4, 0]])

In [204]:
# find out details about a tensor
print(random_int_tensor)
print(f"Data type of tensor: {random_int_tensor.dtype}")
print(f"Shape of tensor: {random_int_tensor.shape}")
print(f"Size of tensor: {random_int_tensor.size()}")
print(f"Device tensor is stored on: {random_int_tensor.device}")
print(f"Number of dimensions: {random_int_tensor.ndim}")


tensor([[2, 2, 3],
        [8, 3, 3],
        [6, 4, 0]])
Data type of tensor: torch.int64
Shape of tensor: torch.Size([3, 3])
Size of tensor: torch.Size([3, 3])
Device tensor is stored on: cpu
Number of dimensions: 2


### Manipulating tensors (tensor operations)

Tensor operations include:
    
        1. Addition
        2. Subtraction
        3. Multiplication
        4. Division
        5. Matrix Multiplication

In [205]:
# create a tensor
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
tensor, tensor+10

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [206]:
tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [207]:
tensor*10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [208]:
tensor/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [209]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)

tensor([[10, 20, 30],
        [40, 50, 60]])

In [210]:
tensor**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

### Matrix Multiplication
Two main ways to perform matrix multiplication in PyTorch:
    
        1. Element-wise multiplication
        2. Matrix multiplication (dot product)

There are two main rules that perform matrix multiplication:
    
        1. The inner dimensions must match
            * `(3,2) @ (3,2)` won't work
            * `(3,2) @ (2,3)` will work
            * `(2,3) @ (3,2)` will work
        2. The resulting matrix has the shape of the outer dimensions
            * `(3,2) @ (2,3)` will result in a `(3,3)` matrix
            * `(2,3) @ (3,2)` will result in a `(2,2)` matrix

In [211]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(2, 3)))

tensor([[0.2569, 0.6962, 0.3646],
        [0.5642, 1.1925, 0.8639],
        [0.4563, 0.9935, 0.6932]])

In [212]:
# Element-wise multiplication
print(tensor,"*",tensor,"=",torch.mul(tensor, tensor))

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]]) = tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [213]:
# matrix multiplication
torch.matmul(tensor, tensor.T)


tensor([[14, 32],
        [32, 77]])

In [214]:
tensor,tensor.T

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [215]:
# matrix multiplication by hand
[1*1+2*2+3*3, 1*4+2*5+3*6], [4*1+5*2+6*3, 4*4+5*5+6*6]

([14, 32], [32, 77])

In [216]:
!time
t = torch.tensor([1,2,3])
m =[]
value =0
for i in range(len(t)):
    value += t[i]*t[i]
    

print(value)

shell  0.00s user 0.01s system 1980% cpu 0.001 total
children  0.00s user 0.00s system 0% cpu 0.001 total
tensor(14)


In [217]:
!time

torch.matmul(t,t)

shell  0.00s user 0.01s system 2305% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor(14)

In [218]:
!time 

torch.matmul(tensor, tensor.T)

shell  0.00s user 0.01s system 1577% cpu 0.001 total
children  0.00s user 0.00s system 0% cpu 0.001 total


tensor([[14, 32],
        [32, 77]])

In [219]:
# @ operator for matrix multiplication
tensor @ tensor.T

tensor([[14, 32],
        [32, 77]])

### One of the most common error in deep learning: shape error

In [224]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
# torch.matmul(tensor_A, tensor_B) # error because of shape
torch.matmul(tensor_A.T, tensor_B),torch.matmul(tensor_A, tensor_B.T)

(tensor([[ 76, 103],
         [100, 136]]),
 tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]))

## Finding min, max, sum, mean, absolute value, standard deviation (tensor aggregation)

In [225]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [226]:
# find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [227]:
# find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [233]:
# find the mean. note that the torch.mean() function requires a float32 tensor
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [234]:
# find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))