<a href="https://colab.research.google.com/github/samiulalimsaad/pytorch-practice/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cpu


## Introduction to PyTorch


### Scaler


In [ ]:
scaler = torch.tensor(7)
scaler


tensor(7)

In [ ]:
scaler.ndim


0

In [ ]:
scaler.shape


torch.Size([])

In [ ]:
scaler.item()


7

### Vector


In [ ]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector


tensor([1, 2, 3, 4, 5])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape


torch.Size([5])

### Matrix


In [ ]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape


torch.Size([2, 3])

In [ ]:
MATRIX[0]


tensor([1, 2, 3])

In [ ]:
MATRIX[1]


tensor([4, 5, 6])

### Tensor


In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape


torch.Size([2, 2, 3])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors


In [ ]:
# Create a random tensor of shape (3, 5)
X = torch.rand(3, 5)
X


tensor([[0.8030, 0.6401, 0.5138, 0.1421, 0.8260],
        [0.9065, 0.7420, 0.4683, 0.5922, 0.9796],
        [0.7512, 0.5726, 0.4839, 0.9965, 0.2629]])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(3, 224, 224)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 5))
zeros


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3, 5))
ones


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [ ]:
# Use torch.range and get deprecated warning, use torch.arange instead
one_to_ten = torch.arange(0, 10)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Use torch.range
one_to_ten2 = torch.arange(start=0, end=10, step=1.1)
one_to_ten2


tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :

1. Tensor is not right data type
2. Tensor is not right shape
3. Tensor is not on right device


In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor(
    data=[1.1, 2.2, 3.3],  # the data to store in the tensor
    dtype=torch.float32,  # the data type of the tensor
    device=None,  # what device to store the tensor on (CPU, GPU)
    requires_grad=False,
)  # whether or not the tensor should be tracked by the gradient descent algorithm
float_32_tensor.dtype, float_32_tensor


(torch.float32, tensor([1.1000, 2.2000, 3.3000]))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)  # convert to float 16
float_16_tensor.dtype, float_16_tensor


(torch.float16, tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16))

In [ ]:
float_32_tensor * float_16_tensor


tensor([ 1.2096,  4.8383, 10.8926])

In [ ]:
int_32_tensor = torch.tensor(data=[1, 2, 3])  # the data to store in the tensor
int_32_tensor.dtype, int_32_tensor


(torch.int64, tensor([1, 2, 3]))

In [ ]:
float_32_tensor * int_32_tensor


tensor([1.1000, 4.4000, 9.9000])

## Getting information from tensors

1. Tensor is not right data type - to get data type form a tensor, can use `tensor.dtype`
2. Tensor is not right shape - to get data type form a tensor, can use `tensor.shape`
3. Tensor is not on right device - to get data type form a tensor, can use `tensor.device`


In [ ]:
# create a tensor of random integers
random_int_tensor = torch.randint(low=0, high=10, size=(3, 3))
random_int_tensor


tensor([[5, 9, 9],
        [2, 7, 4],
        [5, 4, 8]])

In [ ]:
# find out details about a tensor
print(random_int_tensor)
print(f"Data type of tensor: {random_int_tensor.dtype}")
print(f"Shape of tensor: {random_int_tensor.shape}")
print(f"Size of tensor: {random_int_tensor.size()}")
print(f"Device tensor is stored on: {random_int_tensor.device}")
print(f"Number of dimensions: {random_int_tensor.ndim}")


tensor([[5, 9, 9],
        [2, 7, 4],
        [5, 4, 8]])
Data type of tensor: torch.int64
Shape of tensor: torch.Size([3, 3])
Size of tensor: torch.Size([3, 3])
Device tensor is stored on: cpu
Number of dimensions: 2


### Manipulating tensors (tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [ ]:
# create a tensor
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
tensor, tensor + 10


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [ ]:
tensor - 10


tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [ ]:
tensor * 10


tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
tensor / 10


tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [ ]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)


tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
tensor**2


tensor([[ 1,  4,  9],
        [16, 25, 36]])

### Matrix Multiplication

Two main ways to perform matrix multiplication in PyTorch:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that perform matrix multiplication:

1. The inner dimensions must match
    - `(3,2) @ (3,2)` won't work
    - `(3,2) @ (2,3)` will work
    - `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the outer dimensions
    - `(3,2) @ (2,3)` will result in a `(3,3)` matrix
    - `(2,3) @ (3,2)` will result in a `(2,2)` matrix


In [ ]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(2, 3)))


tensor([[1.1017, 1.0073, 0.9080],
        [1.3178, 1.1731, 1.0798],
        [1.1488, 1.0005, 0.9369]])

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor, "=", torch.mul(tensor, tensor))


tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]]) = tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor.T)


tensor([[14, 32],
        [32, 77]])

In [ ]:
tensor, tensor.T


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [ ]:
# matrix multiplication by hand
[1 * 1 + 2 * 2 + 3 * 3, 1 * 4 + 2 * 5 + 3 * 6], [
    4 * 1 + 5 * 2 + 6 * 3,
    4 * 4 + 5 * 5 + 6 * 6,
]


([14, 32], [32, 77])

In [ ]:
!time
t = torch.tensor([1,2,3])
m =[]
value =0
for i in range(len(t)):
    value += t[i]*t[i]
    

print(value)

shell  0.00s user 0.01s system 2250% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total
tensor(14)


In [ ]:
!time

torch.matmul(t,t)

shell  0.00s user 0.01s system 2523% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor(14)

In [ ]:
!time 

torch.matmul(tensor, tensor.T)

shell  0.00s user 0.01s system 2132% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor([[14, 32],
        [32, 77]])

In [ ]:
# @ operator for matrix multiplication
tensor @ tensor.T


tensor([[14, 32],
        [32, 77]])

### One of the most common error in deep learning: shape error


In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
# torch.matmul(tensor_A, tensor_B) # error because of shape
torch.matmul(tensor_A.T, tensor_B), torch.matmul(tensor_A, tensor_B.T)


(tensor([[ 76, 103],
         [100, 136]]),
 tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]))

## Finding min, max, sum, mean, absolute value, standard deviation (tensor aggregation)


In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [ ]:
# find the mean. note that the torch.mean() function requires a float32 tensor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()


(tensor(450), tensor(450))

### finding the positional maximum and minimum


In [ ]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the position in tensor that has the minimum value

x.argmin(), x.min()


(tensor(0), tensor(0))

In [ ]:
# find the position in tensor that has the maximum value

x.argmax(), x.max()


(tensor(9), tensor(90))

In [ ]:
tensor_A, tensor_A.argmax()


(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor(5))

## Reshaping, stacking, squeezing, un-squeezing

-   Reshaping - reshape an input tensor to a defined shape
-   view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
-   stack - combine multiple tensors on top of each other (vertically - vstack) or side by side (horizontally h-stack)
-   squeeze - remove all `1` dimensions from a tensor
-   unsqueeze - add a dimension of size `1` to a tensor
-   permute - return a view of an input tensor with its dimensions permuted (swapper) in a certain order


In [ ]:
x = torch.arange(1.0, 10.0)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add a dimension to the tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped2 = x.reshape(9, 1)
x_reshaped2, x_reshaped2.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because they are the same tensor and shares the same memory)
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze the tensor - remove all dimensions of size 1
x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# unsqueeze the tensor - add a dimension of size 1

x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape


(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [ ]:
# permute  - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # (height, width, channels)
x_original[0][0][0], x_original.shape


(tensor(0.1763), torch.Size([224, 224, 3]))

In [ ]:
# permute the tensor to rearrange the dimensions
x_permuted = x_original.permute(2, 0, 1)  # (channels, height, width)
x_permuted[0][0][0], x_permuted.shape


(tensor(0.1763), torch.Size([3, 224, 224]))

In [ ]:
x_permuted[0, 0, 0], x_permuted.shape


(tensor(0.1763), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

-   indexing with PyTorch is similar with numpy


In [ ]:
# creating a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on our new tensor

x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on middle bracket (dim=1)
x[0, 0], x[0][0]  # both are same


(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#  lets index on the most inner bracket (last dimension)
x[0, 0, 0], x[0][0][0]


(tensor(1), tensor(1))

In [ ]:
#  you can use ":" to select "all" of a target dimension

x, x[:, 0], x[:, 0, 0], x[:, 0, 0][0]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3]]),
 tensor([1]),
 tensor(1))

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x, x[:, :, 1]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

In [ ]:
#  get all values of the 0 dimension but only 1 index of 1st and 2nd dimensions
x, x[:, 1, 1], x[0, 1, 1]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([5]),
 tensor(5))

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x, x[0, 0, :], x[0, 0], x[0][0]


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]))

In [ ]:
# index on x to return 9

print(x, x[:, 2, 2], x[0, 2, 2])

# index on x to return 3, 6, 9

print(x, x[:, :, 2])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) tensor([9]) tensor(9)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

NumPy is a popular scientific numerical computing library for Python.

And because of this, PyTorch has functionality to interact with NumPy.

-   Data in NumPy, want in PyTorch tensors -> `torch.from_numpy(ndarray)`
-   PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
#  Numpy Array to Tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change th evalue of array and waht will this do to `tensor`

array = array + 1
print(array, tensor)

tensor = tensor + 1

print(array, tensor)


[ 7.  8.  9. 10. 11. 12. 13.] tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)
[ 7.  8.  9. 10. 11. 12. 13.] tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [ ]:
#  tensor to numpy array
tensor = torch.arange(1.0, 8.0)
array = tensor.numpy()
tensor, array


(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [ ]:
# Change the tensor and what will this do to `array`
tensor = tensor + 1
print(tensor, array)


tensor([2., 3., 4., 5., 6., 7., 8.]) [1. 2. 3. 4. 5. 6. 7.]


In [ ]:
# Change the array and what will this do to `tensor`
array = array + 1
print(tensor, array)


tensor([2., 3., 4., 5., 6., 7., 8.]) [3. 4. 5. 6. 7. 8. 9.]


## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data ->again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness.


In [ ]:
torch.rand(3, 3)  # will create always random numbers between 0 and 1


tensor([[0.3489, 0.9981, 0.8182],
        [0.3984, 0.0352, 0.4393],
        [0.8154, 0.2663, 0.7201]])

In [ ]:
# create two random tensors
random_tensor_a = torch.rand(3, 3)
random_tensor_b = torch.rand(3, 3)


random_tensor_a, random_tensor_b, random_tensor_a == random_tensor_b


(tensor([[0.2962, 0.1049, 0.8422],
         [0.2231, 0.4661, 0.0894],
         [0.6148, 0.0865, 0.0531]]),
 tensor([[4.2539e-01, 9.5411e-01, 2.8765e-04],
         [4.8304e-01, 6.6858e-01, 3.7690e-01],
         [9.6109e-01, 4.4466e-01, 3.5286e-01]]),
 tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]))

In [ ]:
# Let's make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 3)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 3)

random_tensor_c, random_tensor_d, random_tensor_c == random_tensor_d


(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [ ]:
!nvidia-smi

zsh:1: command not found: nvidia-smi
