In [247]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cpu


## Introduction to PyTorch


### Scaler


In [248]:
scaler = torch.tensor(7)
scaler


tensor(7)

In [249]:
scaler.ndim


0

In [250]:
scaler.shape


torch.Size([])

In [251]:
scaler.item()


7

### Vector


In [252]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector


tensor([1, 2, 3, 4, 5])

In [253]:
vector.ndim


1

In [254]:
vector.shape


torch.Size([5])

### Matrix


In [255]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [256]:
MATRIX.ndim


2

In [257]:
MATRIX.shape


torch.Size([2, 3])

In [258]:
MATRIX[0]


tensor([1, 2, 3])

In [259]:
MATRIX[1]


tensor([4, 5, 6])

### Tensor


In [260]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [261]:
TENSOR.ndim


3

In [262]:
TENSOR.shape


torch.Size([2, 2, 3])

In [263]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6]])

### Random Tensors


In [264]:
# Create a random tensor of shape (3, 5)
X = torch.rand(3, 5)
X


tensor([[0.3772, 0.3751, 0.8823, 0.8466, 0.7748],
        [0.4475, 0.4984, 0.1757, 0.5802, 0.2493],
        [0.4262, 0.9549, 0.6008, 0.2929, 0.5950]])

In [265]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(3, 224, 224)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [266]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 5))
zeros


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [267]:
# create a tensor of all ones
ones = torch.ones(size=(3, 5))
ones


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [268]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [269]:
# Use torch.range and get deprecated warning, use torch.arange instead
one_to_ten = torch.arange(0, 10)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
# Use torch.range
one_to_ten2 = torch.arange(start=0, end=10, step=1.1)
one_to_ten2


tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])

In [271]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data types

**Note:** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :

1. Tensor is not right data type
2. Tensor is not right shape
3. Tensor is not on right device


In [272]:
# float 32 tensor
float_32_tensor = torch.tensor(
    data=[1.1, 2.2, 3.3],  # the data to store in the tensor
    dtype=torch.float32,  # the data type of the tensor
    device=None,  # what device to store the tensor on (CPU, GPU)
    requires_grad=False,
)  # whether or not the tensor should be tracked by the gradient descent algorithm
float_32_tensor.dtype, float_32_tensor


(torch.float32, tensor([1.1000, 2.2000, 3.3000]))

In [273]:
float_16_tensor = float_32_tensor.type(torch.float16)  # convert to float 16
float_16_tensor.dtype, float_16_tensor


(torch.float16, tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16))

In [274]:
float_32_tensor * float_16_tensor


tensor([ 1.2096,  4.8383, 10.8926])

In [275]:
int_32_tensor = torch.tensor(data=[1, 2, 3])  # the data to store in the tensor
int_32_tensor.dtype, int_32_tensor


(torch.int64, tensor([1, 2, 3]))

In [276]:
float_32_tensor * int_32_tensor


tensor([1.1000, 4.4000, 9.9000])

## Getting information from tensors

1. Tensor is not right data type - to get data type form a tensor, can use `tensor.dtype`
2. Tensor is not right shape - to get data type form a tensor, can use `tensor.shape`
3. Tensor is not on right device - to get data type form a tensor, can use `tensor.device`


In [277]:
# create a tensor of random integers
random_int_tensor = torch.randint(low=0, high=10, size=(3, 3))
random_int_tensor


tensor([[8, 6, 4],
        [8, 4, 2],
        [1, 3, 2]])

In [278]:
# find out details about a tensor
print(random_int_tensor)
print(f"Data type of tensor: {random_int_tensor.dtype}")
print(f"Shape of tensor: {random_int_tensor.shape}")
print(f"Size of tensor: {random_int_tensor.size()}")
print(f"Device tensor is stored on: {random_int_tensor.device}")
print(f"Number of dimensions: {random_int_tensor.ndim}")


tensor([[8, 6, 4],
        [8, 4, 2],
        [1, 3, 2]])
Data type of tensor: torch.int64
Shape of tensor: torch.Size([3, 3])
Size of tensor: torch.Size([3, 3])
Device tensor is stored on: cpu
Number of dimensions: 2


### Manipulating tensors (tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [279]:
# create a tensor
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
tensor, tensor + 10


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [280]:
tensor - 10


tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [281]:
tensor * 10


tensor([[10, 20, 30],
        [40, 50, 60]])

In [282]:
tensor / 10


tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [283]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)


tensor([[10, 20, 30],
        [40, 50, 60]])

In [284]:
tensor**2


tensor([[ 1,  4,  9],
        [16, 25, 36]])

### Matrix Multiplication

Two main ways to perform matrix multiplication in PyTorch:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that perform matrix multiplication:

1. The inner dimensions must match
    - `(3,2) @ (3,2)` won't work
    - `(3,2) @ (2,3)` will work
    - `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the outer dimensions
    - `(3,2) @ (2,3)` will result in a `(3,3)` matrix
    - `(2,3) @ (3,2)` will result in a `(2,2)` matrix


In [285]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(2, 3)))


tensor([[0.4360, 0.9709, 0.6957],
        [0.3686, 0.7984, 0.5750],
        [0.5998, 1.2284, 0.8940]])

In [286]:
# Element-wise multiplication
print(tensor, "*", tensor, "=", torch.mul(tensor, tensor))


tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]]) = tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [287]:
# matrix multiplication
torch.matmul(tensor, tensor.T)


tensor([[14, 32],
        [32, 77]])

In [288]:
tensor, tensor.T


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [289]:
# matrix multiplication by hand
[1 * 1 + 2 * 2 + 3 * 3, 1 * 4 + 2 * 5 + 3 * 6], [
    4 * 1 + 5 * 2 + 6 * 3,
    4 * 4 + 5 * 5 + 6 * 6,
]


([14, 32], [32, 77])

In [290]:
!time
t = torch.tensor([1,2,3])
m =[]
value =0
for i in range(len(t)):
    value += t[i]*t[i]
    

print(value)

shell  0.00s user 0.01s system 2232% cpu 0.001 total
children  0.00s user 0.00s system 0% cpu 0.001 total
tensor(14)


In [291]:
!time

torch.matmul(t,t)

shell  0.00s user 0.01s system 2590% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor(14)

In [292]:
!time 

torch.matmul(tensor, tensor.T)

shell  0.00s user 0.01s system 2429% cpu 0.000 total
children  0.00s user 0.00s system 0% cpu 0.000 total


tensor([[14, 32],
        [32, 77]])

In [293]:
# @ operator for matrix multiplication
tensor @ tensor.T


tensor([[14, 32],
        [32, 77]])

### One of the most common error in deep learning: shape error


In [294]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
# torch.matmul(tensor_A, tensor_B) # error because of shape
torch.matmul(tensor_A.T, tensor_B), torch.matmul(tensor_A, tensor_B.T)


(tensor([[ 76, 103],
         [100, 136]]),
 tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]))

## Finding min, max, sum, mean, absolute value, standard deviation (tensor aggregation)


In [295]:
# create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [296]:
# find the min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [297]:
# find the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [298]:
# find the mean. note that the torch.mean() function requires a float32 tensor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [299]:
# find the sum
torch.sum(x), x.sum()


(tensor(450), tensor(450))

### finding the positional maximum and minimum


In [300]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [301]:
# find the position in tensor that has the minimum value

x.argmin(), x.min()


(tensor(0), tensor(0))

In [302]:
# find the position in tensor that has the maximum value

x.argmax(), x.max()


(tensor(9), tensor(90))

In [303]:
tensor_A, tensor_A.argmax()


(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor(5))

## Reshaping, stacking, squeezing, un-squeezing

-   Reshaping - reshape an input tensor to a defined shape
-   view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
-   stack - combine multiple tensors on top of each other (vertically - vstack) or side by side (horizontally h-stack)
-   squeeze - remove all `1` dimensions from a tensor
-   unsqueeze - add a dimension of size `1` to a tensor
-   permute - return a view of an input tensor with its dimensions permuted (swapper) in a certain order


In [304]:
x = torch.arange(1.0, 10.0)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [305]:
# add a dimension to the tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [306]:
x_reshaped2 = x.reshape(9, 1)
x_reshaped2, x_reshaped2.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [307]:
# change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [308]:
# changing z changes x (because they are the same tensor and shares the same memory)
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [309]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [310]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [311]:
# squeeze the tensor - remove all dimensions of size 1
x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [312]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [313]:
# unsqueeze the tensor - add a dimension of size 1

x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [318]:
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape


(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [329]:
# permute  - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # (height, width, channels)
x_original[0][0][0], x_original.shape


(tensor(0.3988), torch.Size([224, 224, 3]))

In [328]:
# permute the tensor to rearrange the dimensions
x_permuted = x_original.permute(2, 0, 1)  # (channels, height, width)
x_permuted[0][0][0], x_permuted.shape


(tensor(0.9777), torch.Size([3, 224, 224]))